# This file is a template, and might need editing before it works on your project.
# Official image for Hashicorp's Terraform. It uses light image which is Alpine
# based as it is much lighter.
#
# Entrypoint is also needed as image by default set `terraform` binary as an
# entrypoint.
image:
  name: registry.gitlab.com/gitlab-org/gitlab-build-images:terraform
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

# Default output file for Terraform plan
variables:
  PLAN: plan.tfplan
  JSON_PLAN_FILE: tfplan.json

cache:
  paths:
    - .terraform

before_script:
  - alias convert_report="jq -r '([.resource_changes[]?.change.actions?]|flatten)|{\"create\":(map(select(.==\"create\"))|length),\"update\":(map(select(.==\"update\"))|length),\"delete\":(map(select(.==\"delete\"))|length)}'"
  - terraform --version
  - terraform init

stages:
  - recognize
  - validate
  - build
  - test
  - deploy
  - commit

checkEnv:
  stage: recognize
  before_script: []
  script:
    - export EVN_TAG=DIT
    - if [ $CI_COMMIT_REF_NAME = "develop" ] ;then ENV_TAG=SIT; fi
    - if [[ $CI_COMMIT_REF_NAME ==  "release"* ]]; then ENV_TAG=UAT; fi
    - if [ $CI_COMMIT_REF_NAME = "master" ]; then ENV_TAG=PROD; fi
    - echo "ENV_TAG=$EVN_TAG" > build.env
  artifacts:
    reports:
      dotenv: build.env

validate:
  stage: validate
  script:
    - terraform -chdir=$ENV_TAG validate
  rules:
    - if: $ENV_TAG =~ /DIT/ && $CI_COMMIT_AUTHOR !~ /WRITE_GIT_TOKEN/

plan:
  stage: build
  script:
    - terraform -chdir=$ENV_TAG plan -out=$PLAN $DESTROY
    - terraform -chdir=$ENV_TAG show --json $PLAN | convert_report > $JSON_PLAN_FILE
  artifacts:
    paths:
      - $ENV_TAG/$PLAN
    reports:
      terraform: $ENV_TAG/$JSON_PLAN_FILE
  rules:
    - if: $ENV_TAG =~ /DIT/ && $CI_COMMIT_AUTHOR !~ /WRITE_GIT_TOKEN/

# Separate apply job for manual launching Terraform as it can be destructive
# action.
apply:
  stage: deploy
  environment:
    name: production
  script:
    - terraform -chdir=$ENV_TAG apply -input=false -auto-approve $DESTROY $PLAN
  dependencies:
    - plan
  rules:
    - if: $ENV_TAG =~ /DIT/ && $CI_COMMIT_AUTHOR !~ /WRITE_GIT_TOKEN/
  artifacts:
    name: terraform-state-$CI_JOB_ID
    paths:
      - $ENV_TAG/terraform.tfstate
      - $ENV_TAG/.terraform.lock.hcl

state:
  stage: commit
  needs:
    - job: apply
  rules:
    - if: $ENV_TAG =~ /DIT/ && $CI_COMMIT_AUTHOR !~ /WRITE_GIT_TOKEN/
  before_script:
    - echo start git commit state changes
  script:
    - git config user.email "$GITLAB_USER_EMAIL"
    - git config user.name "$GITLAB_USER_NAME"
    - git checkout $CI_COMMIT_BRANCH
    - git config -l
    - git diff -b
    - git commit $ENV_TAG/terraform.tfstate -m "Update terraform.tfstate after terraform apply in job $CI_JOB_ID triggered by $GITLAB_USER_NAME" || true
    - git push https://WRITE_GIT_TOKEN:${WRITE_GIT_TOKEN}@git.epam.com/ethan_li/aws-terraform-freetier.git $CI_COMMIT_BRANCH
